Vagrant.configure("2") do |config|
	(1..3).each do |i|
		config.vm.define "k8s-node#{i}" do |node|
			# 设置虚拟机的BOX
			node.vm.box = "centos/7"

			# 禁用自动更新检查
			# node.vm.box_check_update = false

			# 设置虚拟机的主机名
			node.vm.hostname = "k8s-node#{i}"

			# 设置虚拟机的IP
			node.vm.network "private_network", ip: "192.168.56.#{99+i}", netmask: "255.255.255.0"

			# 设置主机和虚拟机的共享目录
			# node.vmsynced_folder "~/Documents/vagrant/share", "/home/vagrant/share"

			# VirtaulBox相关设置
			node.vm.provider "virtualbox" do |v|
				# 设置虚拟机的名称
				v.name = "k8s-node#{i}"
				# 设置虚拟机的内存大小建议4g,我的内存不够设置3g
				v.memory = 3072
				# 设置虚拟机的CPU个数
				v.cpus = 4
			end
		end
	end
end